### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by linakherchi** [aishnair22/aura-beauty#3]
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

**Comment by linakherchi** [comment]
1) Does every product has a shade ?
2) Do you want a category table that a product belongs_to ? 
3) I am seeing `index on user_id, unique: true` on cart_items table that does not have a `user_id` column?
4) Could you please change the foreign key references to be written in the same way as BlueBird?
5) Could you please back_tick column names? 

Thanks

**Comment by aishnair22** [comment]
I have updated my schema to reflect these changes.
