### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by linakherchi** [aishnair22/aura-beauty#4]
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

**Comment by linakherchi** [comment]
1) Having a currentCartId sounds in your session slice of state is a great idea ! I love it
2) Did we end up saying we did not want a category table? I am thinking about it again and feel it would be more efficient to have a table because you do not want to pull the data from the backend every time a user clicks on a new category.

Let me know your thoughts ! At the end of the day, it all comes down to finding ways to reduce the number of backend / database pings.

**Comment by aishnair22** [comment]
We said I could access the categories by doing a Product.find_by(category: ...). That actually does sound like too many database pings, so maybe I should do a categories table?

**Comment by aishnair22** [comment]
I decided to add a categories table, so I updated my schema and my state shape :)
