### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by linakherchi** [aishnair22/aura-beauty#5]
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

**Comment by linakherchi** [comment]
**USERS**
1) Do you need `/api/users/:user_id` if you can access that user's info through the current user's id ? 

**CATEGORIES**
1) Regarding your question related to `/api/categories/category_id`, you might need a nested route `/api/categories/category_id/products` to extract all of the products belonging to a certain category.

**CART ITEMS**
1) You do not need to nest the cart_items because you should be able to give cart_items access to only the logged in user, which you can find through the current_user's id.
+ If you have an association on your user model such as @user.cart, you do not need to nest `cart_items` under `cart_id` neither.
2) I do not think you need a `GET` for you cart nor for your cart items - pretty sure you can find associations to do `current_user.cart` and `current_user.cart.cart_items`

**REVIEWS**
1) No need of nested routes for `edit` and `delete` reviews because you do not need to know that a review belongs to a certain product to remove or edit it. As long as you have its ID, you will be able to do that !

Let me know if you have questions

**Comment by aishnair22** [comment]
I updated most of these, but I slacked you 2 questions I have!

**Comment by linakherchi** [comment]
Thanks !
